### ISSUE TITLE
05/2022 ix Abo

### ISSUE THREAD

**Issue by hadesxp** [AlexanderMelde/dl_for_heise#1]
Hi,
currently there is a special offer where one can get one digital version of the next ix and access to the digital archive.

Using your script. the thumbnails can be downloaded, but it does not find the pdf:

`Server did not serve a valid pdf (instead text/html;charset=UTF-8).`

Retry every 15secs, max attemps 3.

**Comment by AlexanderMelde** [comment]
Can you try downloading the mentioned _text/html_ file and read its content? 
It might tell you the reason for failing, e.g. not logged in or invalid subscription etc.

**Comment by hadesxp** [comment]
> Can you try downloading the mentioned _text/html_ file and read its content? It might tell you the reason for failing, e.g. not logged in or invalid subscription etc.

There might be two faults:
1) My abo seems to be limited, thus not including full access to the full archive of ix. By using the webbrowser, only a few can be downloaded.

2) Downloading the pdf via the browser, there is a countdown 60 secs until you get the download, like with the one-click-hosters. This might also break the script.

So, I downloaded it manually :-)

**Comment by AlexanderMelde** [comment]
Alright, glad you found a solution. 
(1) seems likely, and i think there is nothing we can do about it. It would be interesting to see if you can download the few that work with both the webbrowser and the script (or only the browser)
(2) is some kind of rate limiting (and custom pdf creation with watermarks), but we know about it and have adapted the script around this (automatic retries)

**Comment by AlexanderMelde** [comment]
I can't reproduce the error at the moment and think a few timeout errors are okay to occur from time to time. If you have any other problems feel free to open a new issue :)
