### ISSUE TITLE
curl: (22) The requested URL Returned error:500

### ISSUE THREAD

**Issue by heilmic** [AlexanderMelde/dl_for_heise#4]
I can't download any magazine from ct or ix. 

The Thumbnail gets downloaded but I think the Header is emtpy ( % 0, Total 0, Reveiced 0 ....)

As you mentioned I checked `https://www.heise.de/select/ct/archiv/2022/1`, there is a "download complete PDF". I can download the it. but there is a countdown to wait ( watermarking process?). 

The script retries 3 times and then there is the "[ERROR] Could not download magazine issue. Please try again later." 

Can you help?
Is the watermarking process the problem?

**Comment by AlexanderMelde** [comment]
You are right, the watermarking process takes some time to complete. The script incorporates a wait time that "hopefully" is long enough to cover the whole watermarking process and download the file after the wait time. If the wait time configured is too short, the behavior you mentioned can occur. Which wait time did you use in the script? Maybe it will work if you set a longer wait time, or try running the same script manually again, a few minutes after the first run.

**Comment by AlexanderMelde** [comment]
Hello @heilmoa, i will close this issue for now. If you need any further assistance feel free to re-open it or create a new issue.
